### ISSUE TITLE
support for different combinations 

### ISSUE THREAD

**Issue by philos3** [fengqiangboy/flutter-nordic-dfu#15]
is there any example code for updating different combinations ? Is it support?

https://devzone.nordicsemi.com/nordic/short-range-guides/b/software-development-kit/posts/getting-started-with-nordics-secure-dfu-bootloader

BL: Bootloader

SD: SoftDevice

APP: Application

![5722 combination](https://user-images.githubusercontent.com/8424317/84354683-e3794680-abf3-11ea-8e14-c0676c0cfa9a.JPG)

**Comment by fengqiangboy** [comment]
这个库调用了官方的DFU库，这个特性可以先看看官方的库支持不，如果官方的库支持的话，可以提供一个实现的demo，我可以整合进来的。

**Comment by fengqiangboy** [comment]
官方原生库：[iOS](https://github.com/NordicSemiconductor/IOS-Pods-DFU-Library) [Android](https://github.com/NordicSemiconductor/Android-DFU-Library)
