### ISSUE TITLE
'flutter_nordic_dfu/flutter_nordic_dfu-Swift.h' file not found

### ISSUE THREAD

**Issue by zwells** [fengqiangboy/flutter-nordic-dfu#4]
Fantastic Library!

I have Android working great for my application, but when I compile for ios, I'm getting this error:

=== BUILD TARGET flutter_nordic_dfu OF PROJECT Pods WITH CONFIGURATION Release ===
    /Users/zwells/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_nordic_dfu-2.2.1/ios/Classes/FlutterNordicDfuPlugin.m:2:9: fatal error: 'flutter_nordic_dfu/flutter_nordic_dfu-Swift.h' file not found
    #import <flutter_nordic_dfu/flutter_nordic_dfu-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~

Do I need to relocate the .h file or is something wrong with my pub get?

**Comment by zwells** [comment]
Going to give this a shot:

This problem happens with all Swift plugins.
flutter/flutter#25676

You are almost right. It seems to work with the following

Bridging Header must be created.
Open the project with XCode. Then choose File -> New -> File -> Swift File.
A dialog will be displayed when creating the swift file(Since this file is deleted, any name can be used.). XCode will ask you if you wish to create Bridging Header, click yes.
Make sure you have use_frameworks! in the Runner block, in ios/Podfile。
Make sure you have SWIFT_VERSION 4.2 selected in you XCode -> Build Settings
Do flutter clean
Go to your ios folder, delete Podfile.lock and Pods folder and then execute pod install --repo-update

**Comment by zwells** [comment]
That did the trick! Again, amazing library!

**Comment by ovestoerholt** [comment]
Hi zwells
I am not able to make the plugin work on iOS. Have tried your comment above but XCode never asks me to create a bridging header.
Could you please help?

**Comment by zwells** [comment]
Here you go:
https://github.com/pauldemarco/flutter_blue/issues/386#issuecomment-540876291
