### ISSUE TITLE
Android 12 issue

### ISSUE THREAD

**Issue by shaileshbakshi** [fengqiangboy/flutter-nordic-dfu#44]
I get this error when ever start DFU process

Process: com.advsolned.asnairguardadmin, PID: 10941
E/AndroidRuntime(10941): java.lang.IllegalArgumentException: com.advsolned.asnairguardadmin: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(10941): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by vincent-iQontrol** [comment]
no.nordicsemi.android:dfu needs to be updated in the build gradle of the plugin, then it works again:

dependencies {
    implementation 'androidx.core:core:1.0.2'
    implementation 'no.nordicsemi.android:dfu:1.12.0'
}

**Comment by shaileshbakshi** [comment]
Thanks for your help. It works now

**Comment by vincent-iQontrol** [comment]
No problem.
I think this issue needs to be open, because the plugin developer needs to fix this.
