### ISSUE TITLE
"DFU ERROR" on iOS randomly

### ISSUE THREAD

**Issue by toddwilson** [fengqiangboy/flutter-nordic-dfu#5]
Often, when attempting a DFU on iOS, the progress gets to 4% and then I'll get the string "DFU FAILED" as the return from FlutterNordicDfu.startDfu(). Is there a way to get more informative error messages from the underlying DFU library?

**Comment by fengqiangboy** [comment]
I think you can run the native project in iOS folder，and then, set breakpoint in the native code.

**Comment by toddwilson** [comment]
The issue ended up being the default value for packetReceiptNotificationParameter (12) can be too high on iPhones XS and XR and this will cause packets to invalidate. Setting to 1 resolves the issue. There is a similar issue on the iOS DFU Pods Github.

**Comment by fengqiangboy** [comment]
NordicSemiconductor/IOS-Pods-DFU-Library#308
