### ISSUE TITLE
xcode report error

### ISSUE THREAD

**Issue by yeyichao** [fengqiangboy/flutter-nordic-dfu#6]
when i build this example for iphone 6 simulater, I received the following error:

Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    Unable to run command 'PBXCp Flutterblue.pbobjc.h' - this target might include its own product.
    Unable to run command 'Touch flutter_blue.framework' - this target might include its own product.
    Unable to run command 'CodeSign flutter_blue.framework' - this target might include its own product.

Could not build the application for the simulator.
Error launching application on iPhone 6s.

**Comment by fengqiangboy** [comment]
Try to go to Build Phases for the target "flutter_blue" and remove the Copy Files phase.
