### ISSUE TITLE
Can't work with flutter_blue 0.6.2

### ISSUE THREAD

**Issue by Airyzone** [fengqiangboy/flutter-nordic-dfu#8]
I have run the example project (which is flutter_blue ^0.5.0), and it works perfectly.
I try to integrate into my project (with plug-in flutter_blue 0.6.2), and it do not work.
Error message is: 
E/DfuBaseService(20455): Connection state change error: 133 newState: 0
E/DfuBaseService(20455): Device not reachable. Check if the device with address xx:xx:xx:xx:xx:xx is in range, is advertising and is connectable
I/flutter (20455): PlatformException(2, DFU FAILED, device address: xx:xx:xx:xx:xx:xx)

I tried to change the example project to flutter_blue 0.6.2, and it will not work. So, I suppose this package will work on flutter_blue ^0.5.0 only.
May you update the package to fit flutter_blue 0.6.2?

**Comment by fengqiangboy** [comment]
The flutter_blue is only use to scan device in example project. In the lib project, we don't need flutter_blue, and all function is no care with flutter_blue.

In this package, it only need bluetooth device id (device mac address in andriod and device uuid in iOS).

And, in our own project, we also use flutter_blue 0.6.2, and it is work fine.

**Comment by fengqiangboy** [comment]
flutter_blue 0.6.0 has change api, so the example code can't work.

**Comment by Airyzone** [comment]
Thank you! I will check my code.
