### ISSUE TITLE
DFU only works while using flutter run

### ISSUE THREAD

**Issue by jspak6** [fengqiangboy/flutter-nordic-dfu#9]
Hi All,

Great work on getting this done. I have been having an issue where using flutter run i have no issues or errors with the zip file in the assets folder or downloading a url and making it into a file and passing it to startDfu. 
However, I have been experiencing an issue when installing it as an apk or putting the app bundle on the play store. I have tried using the example you have provided as well  and I have the same issue. I have narrowed it down to a try catch error at stratDfu. 
I am using flutter 1.10.7, flutter-nordic-dfu v 2.3.0, and flutter-blue v 0.6.2.

Any help would be great. 
Thanks

**Comment by fengqiangboy** [comment]
Can you put more error detail message ?

**Comment by jspak6** [comment]
I was able to print an error message to the screen. PlatformExeception(2,DFU FAILED,device address: xx:xx:xx:xx:xx:xx).

**Comment by bjornwilliam** [comment]
I am having the same issue. Trying to figure it out, but no solution yet.

**Comment by zwells** [comment]
@fengqiangboy @bjornwilliam Edit3 fixed the issue for me as well! Thank You!

**Comment by MrHazee** [comment]
Edit3 worked for me as well! Thanks a lot
